
# API Node.ts + React + TypeScript + MongoDB + MQTT + EMQX + Prometheus + Grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder-studio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder-studio
  template:
    metadata:
      labels:
        app: decoder-studio
    spec:
      containers:
        - name: decoder-studio
          image: alexsandrojsilva0/decoder-studio-ts:latest
          ports:
            - containerPort: 3001
          env:
            # Configurações do Servidor
            - name: PORT
              value: "3001"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
            - name: USE_HTTPS
              value: "false"
            - name: SSL_KEY_PATH
              value: "./src/certs/key.pem"
            - name: SSL_CERT_PATH
              value: "./src/certs/cert.pem"

            # Banco de Dados MongoDB
            - name: DB_USER
              value: "ajs6_db_user"
            - name: DB_PASS
              value: "r9e3h7lyrZZAppdO"
            - name: DB_HOST
              value: "clusterlab.f78w4n4.mongodb.net/"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "modcs"

            # Conexão MQTT
            - name: MQTT_BROKER
              value: "mqtts://eaa7d5aa.ala.eu-central-1.emqxsl.com:8883"
            - name: MQTT_TOPIC
              value: "moto/can"
            - name: MQTT_USER
              value: "modcs"
            - name: MQTT_PASSWORD
              value: "12345678"
---
apiVersion: v1
kind: Service
metadata:
  name: decoder-studio
spec:
  type: LoadBalancer # ALTERADO: De LoadBalancer para NodePort
  selector:
    app: decoder-studio
  ports:
    - name: tcp
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31443
