name: Build and Push Docker Hub Image

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que a Action faça commit da nova versão
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Bump package.json version
        id: version
        run: |
          # Configura o git local para autorizar o commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Incrementa a versão no package.json usando npm
          NEW_VERSION=$(npm version ${{ inputs.bump_type }} --no-git-tag-version)
          # Remove o prefixo 'v' retornado pelo npm (ex: v1.0.1 -> 1.0.1)
          CLEAN_VERSION=${NEW_VERSION#v}
          
          echo "NEW_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/decoder-studio-ts:${{ env.NEW_VERSION }}
            ${{ env.DOCKER_USER }}/decoder-studio-ts:latest

      - name: Commit and Push new version to GitHub
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): bump version to ${{ env.NEW_VERSION }} [skip ci]"
          git tag "v${{ env.NEW_VERSION }}"
          git push origin HEAD:${{ github.ref_name }} --tags